#!/usr/bin/env bash
mkdir -p "outputs"
for file in tests/*; do
	[ -e "$file" ] || continue
	output_file="outputs/${file##*/}"

	bin/json_merger "$file" --javascript --pretty > "$output_file"

	result=$(diff "expected_outputs/${file##*/}" "$output_file")
	if [ $? -eq 0 ]; then
		echo "$file passed test"
	else
		>&2 echo "$file failed"
		>&2 echo "$result"
		exit 1
	fi
done
